"""Create deploy/.env.demo with fresh secrets for the Docker demo. Never overwrites; the file is git-ignored.

Usage:  python deploy/gen_secrets.py
Passwords are written to the file only (not printed). Add LLM keys there by hand if you want live agents.
"""

import base64
import secrets
import sys
from pathlib import Path

try:
    from nacl.public import PrivateKey
except ImportError:
    sys.exit("pip install PyNaCl first (it is in backend/requirements.txt)")

target = Path(__file__).with_name(".env.demo")
if target.exists():
    sys.exit(f"{target} already exists; delete it to regenerate (new keys make old reports unreadable)")


def b64(raw: bytes) -> str:
    return base64.b64encode(raw).decode()


lines = [
    "# Generated by deploy/gen_secrets.py. Git-ignored. Do not share.",
    "SAHAY_DEV=0",
    f"SAHAY_JWT_SECRET={secrets.token_urlsafe(48)}",
    f"SAHAY_SERVER_X25519_SECRET_KEY={b64(bytes(PrivateKey.generate()))}",
    f"SAHAY_SERVER_ED25519_SECRET_KEY={b64(secrets.token_bytes(32))}",
    f"SAHAY_PII_ENCRYPTION_KEY={b64(secrets.token_bytes(32))}",
    f"SAHAY_SEED_ADMIN_PASSWORD={secrets.token_urlsafe(12)}",
    f"SAHAY_SEED_SERVICE_PASSWORD={secrets.token_urlsafe(12)}",
    "SAHAY_CORS_ORIGINS=https://localhost,capacitor://localhost",
    "SAHAY_LLM_MODE=mock",
    "SAHAY_SEARCH_MODE=mock",
    "SAHAY_STT_MODE=mock",
]
target.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {target}")
