// @vitest-environment node
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import sodium from "libsodium-wrappers";
import { beforeAll, describe, expect, it } from "vitest";
import {
  buildEnvelope,
  PayloadError,
  signingInput,
  validatePayload,
  verifyReceipt,
  type ReportPayload,
  type ServerKey,
} from "./envelope";

// contract/crypto-test-vector.json is the shared fixture (generated by backend/scripts/gen_test_vector.py).
const vector = JSON.parse(
  readFileSync(
    resolve(__dirname, "../../../../contract/crypto-test-vector.json"),
    "utf8",
  ),
);
const b = (s: string) => sodium.from_base64(s, sodium.base64_variants.ORIGINAL);
const serverKey: ServerKey = {
  key_id: vector.envelope.key_id,
  x25519_public_key: vector.server.box_public_key,
  ed25519_public_key: vector.server.verify_key,
};
const identity = {
  deviceId: vector.envelope.device_id as string,
  seed: undefined as unknown as Uint8Array,
};
const payload = JSON.parse(vector.plaintext_json) as ReportPayload;

beforeAll(async () => {
  await sodium.ready;
  identity.seed = b(vector.device.signing_seed);
});

describe("envelope against the frozen contract vector", () => {
  it("signing input matches the vector byte for byte", () => {
    const e = vector.envelope;
    const msg = signingInput(
      e.report_id,
      e.device_id,
      e.created_at,
      b(e.ciphertext),
    );
    expect(sodium.to_base64(msg, sodium.base64_variants.ORIGINAL)).toBe(
      vector.signing_input_b64,
    );
  });

  it("the vector payload passes client validation", () => {
    expect(() => validatePayload(payload)).not.toThrow();
  });

  it("builds an envelope the server can open and the device key verifies", async () => {
    const env = await buildEnvelope(payload, identity, serverKey, {
      reportId: vector.envelope.report_id,
      now: new Date("2026-10-09T10:15:00Z"),
    });
    expect(env).toMatchObject({
      envelope_version: 1,
      report_id: vector.envelope.report_id,
      device_id: vector.envelope.device_id,
      created_at: "2026-10-09T10:15:00Z",
      ttl: 5,
      key_id: "k1",
    });
    // Server side: open the sealed box with the server secret, plaintext must be our payload.
    const plain = sodium.crypto_box_seal_open(
      b(env.ciphertext),
      b(vector.server.box_public_key),
      b(vector.server.box_secret_key),
    );
    expect(JSON.parse(sodium.to_string(plain))).toEqual(payload);
    // Signature verifies over report_id|device_id|created_at|ciphertext with the device public key.
    const msg = signingInput(
      env.report_id,
      env.device_id,
      env.created_at,
      b(env.ciphertext),
    );
    expect(
      sodium.crypto_sign_verify_detached(
        b(env.signature),
        msg,
        b(vector.device.public_key),
      ),
    ).toBe(true);
  });

  it("is deterministic only in the signature: two seals of one payload differ, both verify", async () => {
    const opts = {
      reportId: vector.envelope.report_id,
      now: new Date("2026-10-09T10:15:00Z"),
    };
    const a = await buildEnvelope(payload, identity, serverKey, opts);
    const c = await buildEnvelope(payload, identity, serverKey, opts);
    expect(a.ciphertext).not.toBe(c.ciphertext);
    expect(a.signature).not.toBe(c.signature);
  });

  it("a tampered ciphertext or created_at no longer verifies", async () => {
    const env = await buildEnvelope(payload, identity, serverKey);
    const ct = b(env.ciphertext);
    ct[0] = (ct[0] ?? 0) ^ 1;
    const bad = signingInput(env.report_id, env.device_id, env.created_at, ct);
    expect(
      sodium.crypto_sign_verify_detached(
        b(env.signature),
        bad,
        b(vector.device.public_key),
      ),
    ).toBe(false);
    const late = signingInput(
      env.report_id,
      env.device_id,
      "2030-01-01T00:00:00Z",
      b(env.ciphertext),
    );
    expect(
      sodium.crypto_sign_verify_detached(
        b(env.signature),
        late,
        b(vector.device.public_key),
      ),
    ).toBe(false);
  });

  it("verifies the vector receipt and rejects a changed time", async () => {
    const r = vector.receipt;
    const receipt = {
      server_time: r.signing_input_utf8.split("|")[1],
      signature: r.signature,
    };
    expect(await verifyReceipt(r.report_id, receipt, serverKey)).toBe(true);
    expect(
      await verifyReceipt(
        r.report_id,
        { ...receipt, server_time: "2030-01-01T00:00:00Z" },
        serverKey,
      ),
    ).toBe(false);
    expect(
      await verifyReceipt(
        r.report_id,
        { ...receipt, signature: "AAAA" },
        serverKey,
      ),
    ).toBe(false);
  });
});

describe("payload validation (mirrors the server so a bad report fails on the phone, not after delivery)", () => {
  const ok: ReportPayload = { ...payload };
  it("needs audio or text", () => {
    const empty = { ...ok, audio: undefined, text: "  " };
    expect(() => validatePayload(empty)).toThrow(PayloadError);
  });
  it("rejects unknown categories and out-of-range locations", () => {
    expect(() =>
      validatePayload({ ...ok, category: "rescue" as never }),
    ).toThrow(PayloadError);
    expect(() =>
      validatePayload({ ...ok, location: { lat: 91, lng: 0 } }),
    ).toThrow(PayloadError);
    expect(() =>
      validatePayload({ ...ok, location: { lat: Number.NaN, lng: 0 } }),
    ).toThrow(PayloadError);
  });
  it("rejects audio over 200 KB", () => {
    const big = sodium.to_base64(
      new Uint8Array(200 * 1024 + 1),
      sodium.base64_variants.ORIGINAL,
    );
    expect(() =>
      validatePayload({
        ...ok,
        audio: { mime: "audio/webm", data: big, duration_s: 90 },
      }),
    ).toThrow(PayloadError);
    const fits = sodium.to_base64(
      new Uint8Array(200 * 1024),
      sodium.base64_variants.ORIGINAL,
    );
    expect(() =>
      validatePayload({
        ...ok,
        audio: { mime: "audio/webm", data: fits, duration_s: 90 },
      }),
    ).not.toThrow();
  });
});
